Fix build with `-Werror=template-id-cdtor` (#5341) (#5422)
error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]
(cherry picked from commit 81f00693974dc603bd67e1afcb0ae85f273071f6)

Co-authored-by: kistlin <83662395+kistlin@users.noreply.github.com>